name: time_zone
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  contacts_service: ^0.6.1+1
  intl_phone_number_input: ^0.7.4
  timezone: ^0.8.0
  path_provider: ^2.0.9
  permission_handler: ^11.3.1
  intl: ^0.17.0
  page_transition: ^2.1.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets: 
    - assets/country_timezones.json
    - assets/clocksbg.jpg
    - assets/earthclock.png
